{
    "Dairy": ["butter", "eggs", "milk", "cheese", "cream", "creme de cassis", "wensleydale cheese"],
    "Vegetables": ["onion", "garlic", "jerusalem artichoke", "cress", "water chestnut",
                   "dulse"],
    "Fruits": ["lemon", "apple", "berries", "kiwi", "grapefruit", "mandarin",
               "kumquat", "boysenberry", "star fruit", "quince", "honeydew", "crabapples"],
    "Baking & Grains": ["rice", "pasta", "flour", "bread", "baking powder", "baking soda"],
    "Added Sweeteners": ["sugar", "brown sugar", "honey", "confectioners sugar", "maple syrup", "syrup", "corn syrup",
                         "molasses", "artificial sweetener", "agave nectar"],
    "Spices": ["cinnamon", "vanilla", "garlic powder", "paprika", "oregano", "chili powder", "red pepper flake",
               "onion flake", "herbes de provence", "chipotle", "dill seed", "fennel seed", "caraway", "cacao",
               "star anise", "savory", "chili paste", "tamarind", "aniseed", "fenugreek", "lavender",
               "old bay seasoning",
               "lemon balm"],
    "Meats": ["chicken breast", "ground beef", "bacon", "sausage", "beef steak"],
    "Oils": ["olive oil", "vegetable oil"],
    "Seasonings": ["bouillon", "ground ginger", "sesame seed", "cream of tartar", "chili sauce", "soya sauce",
                   "apple cider", "hoisin sauce", "liquid smoke", "rice wine", "vegetable bouillon", "poppy seed",
                   "balsamic glaze"
                   "cassia"],
    "Sauces": ["tomato sauce", "tomato paste", "salsa", "pesto", "alfredo sauce", "beef gravy", "curry paste",
               "chicken gravy", "cranberry sauce", "turkey gravy", "mushroom gravy", "sausage gravy", "onion gravy",
               "cream gravy", "pork gravy", "tomato gravy", "giblet gravy"],
    "Legumes": ["green beans", "peas", "black beans", "chickpea", "lentil", "refried beans", "hummus", "chili beans",
                "lima beans", "kidney beans", "pinto beans", "edamame", "split peas", "snap peas", "soybeans",
                "cannellini beans", "navy beans", "french beans", "red beans", "great northern beans", "fava beans"],
    "Alcohol": ["white wine", "beer", "red wine"],
    "Dairy Alternatives": ["rice milk", "hemp milk",
                           "non dairy creamer"],
    "Desserts & Snacks": ["chocolate", "mint jelly", "currant jelly", "lemon jelly",
                          "quince jelly"],
    "Beverages": ["coffee", "orange juice", "tea", "green tea", "apple juice", "tomato juice", "coke",
                  "club soda",
                  "sprite", "kool aid", "grenadine", "margarita mix", "cherry juice", "pepsi", "mountain dew"]}
